pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                bat 'python -m py_compile 
25-simple-python-pyinstaller-app/sources/add2vals.py 
25-simple-python-pyinstaller-app/sources/calc.py' 
                stash(name: 'compiled-results', includes: 'sources/*.py*') 
            }
        }
    }
}

